# The cron job runner
cron:
  disable: true

# The version of the application
version: 0.1.0

# The gRPC address
grpc:
  disable: true

# The http address
http:
  disable: true

# The global logging level and format
log:
  format: logfmt
  level: debug

# The environment of the application, one of production, development, staging, testing or local
env: local

# The name of the application
name: app

kafka:
  reader:
    default:
      brokers:
        - 127.0.0.1:9092
      groupID: "123"
      topic: "test"
      startOffset: -1
    foo:
      brokers:
        - 127.0.0.1:9092
      groupID: "444"
      topic: "test"
      startOffset: -1
kafkaMetrics:
  interval: 15s
# The database configuration
gorm:
  default:
    database: sqlite
    dsn: ":memory:"
gormMetrics:
  interval: 15s

