# The cron job runner
cron:
  disable: true

# The version of the application
version: 0.1.0

# The gRPC address
grpc:
  addr: :9090
  disable: false

# The http address
http:
  addr: :8080
  disable: false

# The global logging level and format
log:
  format: logfmt
  level: debug

# The environment of the application, one of production, development, staging, testing or local
env: local

# The name of the application
name: app


kafka:
  reader:
    default:
      brokers:
        - 127.0.0.1:9092
      groupID: "123"
      topic: "test"
      partition: 0
      queue_capacity: 0
      minBytes: 0
      maxBytes: 0
      maxWait: 0s
      readLagInterval: 0s
      heartbeatInterval: 0s
      commitInterval: 0s
      partitionWatchInterval: 0s
      watchPartitionChanges: false
      sessionTimeout: 0s
      rebalanceTimeout: 0s
      joinGroupBackoff: 0s
      retentionTime: 0s
      startOffset: -1
      readBackoffMin: 0s
      readBackoffMax: 0s
      maxAttempts: 0
    foo:
      brokers:
        - 127.0.0.1:9092
      groupID: "444"
      topic: "test"
      partition: 0
      queue_capacity: 0
      minBytes: 0
      maxBytes: 0
      maxWait: 0s
      readLagInterval: 0s
      heartbeatInterval: 0s
      commitInterval: 0s
      partitionWatchInterval: 0s
      watchPartitionChanges: false
      sessionTimeout: 0s
      rebalanceTimeout: 0s
      joinGroupBackoff: 0s
      retentionTime: 0s
      startOffset: -1
      readBackoffMin: 0s
      readBackoffMax: 0s
      maxAttempts: 0
  writer:
    default:
      brokers:
        - 127.0.0.1:9092
      topic: "test"
      maxAttempts: 10
      batchSize: 1000
      batchBytes: 1000
      batchTimeout: 5s
      readTimeout: 5s
      writeTimeout: 5s
      rebalanceInterval: 60s
      requiredAcks: 0
      async: false
kafkaMetrics:
  interval: 15s

